WhiteBoard/base/urls.py
from django.conf.urls import patterns, url

from WhiteBoard.base import views

urlpatterns = patterns(
    '',
    url(r'^login/', views.login, name='login'),
    url(r'^auth/', views.auth, name='auth'),
    url(r'^/$', views.index, name='default'),
    url(r'^$', views.index, name='default'),
    url(r'^index/', views.index, name='index'),
    url(r'^invalidLogin', views.invalidLogin, name='invalidLogin'),
    url(r'^loginRequired', views.loginRequired, name='loginRequired'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^home', views.home, name='home'),
    url(r'^announcements', views.announcements, name='announcments'),
    url(r'^create_announcement', views.CreateAnnouncementView.as_view(),
        name='create_announcements'),
)

WhiteBoard/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('WhiteBoard.base.urls', namespace='base')),
    url(r'^', include('WhiteBoard.grades.urls', namespace='grades')),
    url(r'^', include('WhiteBoard.calendar.urls', namespace='calendar')),
]

WhiteBoard/base/models.py
from django.db import models
from django.contrib.auth.models import User


class Person(models.Model):
    # TA, ADMN, PROF, or STUD
    type = models.CharField(max_length=4)
    user = models.ForeignKey(User)


class Announcement(models.Model):
    poster = models.ForeignKey(Person)
    date_posted = models.DateField(auto_now=False, auto_now_add=True)
    content = models.CharField(max_length=300)
    title = models.CharField(max_length=50)

    class Meta:
        ordering = ['-date_posted']

WhiteBoard/base/forms.py
import smtplib

from django import forms
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegistrationForm(UserCreationForm):

    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=50, required=True)
    last_name = forms.CharField(max_length=50, required=True)

    class Meta:
        model = User
        fields = ('username',
                  'password1',
                  'password2',
                  'email',
                  'first_name',
                  'last_name')

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.set_password(self.cleaned_data['password1'])

        if commit is True:
            user.save()
        return user

WhiteBoard/base/views.py
from os import listdir
from os.path import isfile, join

from django.contrib.auth import (authenticate, login as authLogin, logout
                                 as authLogout, update_session_auth_hash)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import (check_password, make_password,
                                         is_password_usable)
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template import RequestContext, loader
from django.templatetags.static import static
from django.utils.decorators import method_decorator
from django.views.generic.edit import FormView, CreateView

from .helpers import getRole
from .models import Announcement, Person


def handler404(request):
    return render(request, '404.html')


def handler500(request):
    return render(request, '500.html')


def logout(request):
    authLogout(request)
    return HttpResponseRedirect(reverse('base:login'))


def login(request):
    return render(request, 'users/login.html')


def auth(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username, password=password)

    if user is not None:
        authLogin(request, user)
        return HttpResponseRedirect(reverse('base:home'))

    else:
        return HttpResponseRedirect(reverse('base:invalidLogin'))


def invalidLogin(request):
    return render(request, 'users/invalidLogin.html')


def index(request):
    if request.user.is_authenticated():
        return home(request)
    else:
        return login(request)


def loginRequired(request):
    return render(request, 'users/loginRequired.html')


@login_required(login_url='/loginRequired')
def home(request):
    announcments = Announcement.objects.all()
    return render(request, 'home.html', {
        'announcements': announcements,
        'role': getRole(request)
    })


@login_required(login_url='/loginRequired')
def announcements(request):
    announcements = Announcement.objects.all()
    return render(request, 'announcements.html', {
        'announcements': announcements,
        'role': getRole(request)
    })


class CreateAnnouncementView(CreateView):
    template_name = 'base_form.html'
    model = Announcement
    fields = ['title', 'content']
    success_url = '/announcements'

    def dispatch(self, *args, **kwargs):
        return super(CreateAnnouncementView, self).dispatch(*args, **kwargs)

    @method_decorator(login_required(login_url='/'))
    def get(self, request):
        self.poster = Person.objects.get(user=request.user)
        return super(CreateAnnouncementView, self).get(self, request)

    @method_decorator(login_required(login_url='/'))
    def post(self, request):
        self.poster = Person.objects.get(user=request.user)
        return super(CreateAnnouncementView, self).post(self, request)

    def form_valid(self, form):
        form.instance.poster = self.poster
        return super(CreateAnnouncementView, self).form_valid(form)

WhiteBoard/base/templates/users/invalidLogin.html
{% extends "base.html" %}
{% block content %}
{% autoescape on %}
<div class="panel panel-default">
    <div class="panel-heading">
            <h3 class="panel-title">Invalid Login</h3>
    </div>
    <div class="panel-body">
        <br>
        <p>
            <b>
                That was not a valid login. Please log in below.
            </b>
        </p>
        <br>
        <form action= "{% url 'base:auth' %}" method= "POST">
        {% csrf_token %}
            <label for="username"> Username: </label>
            <input type="text" name="username" value="" placeholder="username" id="username">
            <br>
            <label for="password"> Password: </label>
            <input type="password" name="password" value="" placeholder="password" id="password">
            <br>
            <br>
            <button type="submit" value="Log in" class="btn btn-default">Submit</button>
        </form>
    </div>
</div>
{% endautoescape %}
{% endblock %}

WhiteBoard/base/templates/users/login.html
{% extends "base.html" %}
{% block content %}
{% autoescape on %}
{% if form.error %}
    <p class="error">Sorry, that was not a valid username or password.</p>
{% endif %}
<div class="panel panel-default">
    <div class="panel-heading">
            <h3 class="panel-title">Log in</h3>
    </div>
    <div class="panel-body">
        <form action= "{% url 'base:auth' %}" method= "POST">
        {% csrf_token %}
            <label for="username"> Username: </label>
            <input type="text" name="username" value="" placeholder="username" id="username">
            <br>
            <label for="password"> Password: </label>
            <input type="password" name="password" value="" placeholder="password" id="password">
            <br>
            <br>
            <button type="submit" value="Log in" class="btn btn-default">Submit</button>
        </form>
    </div>
</div>
{% endautoescape %}
{% endblock %}

WhiteBoard/base/templates/users/loginRequired.html
{% extends "base.html" %}
{% block content %}
{% autoescape on %}
<div class="panel panel-default">
    <div class="panel-heading">
            <h3 class="panel-title">Login Required</h3>
    </div>
    <div class="panel-body">
        <br>
        <p>
            <b>
                You need to be logged in to view this page. Please log in below.
            </b>
        </p>
        <br>
        <form action= "{% url 'base:auth' %}" method= "POST">
        {% csrf_token %}
            <label for="username"> Username: </label>
            <input type="text" name="username" value="" placeholder="username" id="username">
            <br>
            <label for="password"> Password: </label>
            <input type="password" name="password" value="" placeholder="password" id="password">
            <br>
            <br>
            <button type="submit" value="Log in" class="btn btn-default">Submit</button>
        </form>
    </div>
</div>
{% endautoescape %}
{% endblock %}